import React from 'react';
import about_img from '../assets/aboutus.jpg';
import './About.css';

const About = () => {
    return (
        <div className='about'>
            <h2>About Recipe Master</h2>
            <img src={about_img} alt='about us' />
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel sapien ex. Pellentesque id ligula scelerisque metus semper vestibulum. Vivamus euismod pharetra lacus at ornare. Fusce sit amet quam urna. Sed facilisis at nibh sit amet tempus. Cras a ex lacus. Nunc hendrerit et massa non placerat. Aliquam non turpis nisl. Nunc accumsan, massa non faucibus semper, nibh tellus cursus lectus, ut mollis arcu eros ac quam. Quisque nunc ante, rhoncus at tellus at, accumsan scelerisque tellus. In non consectetur quam. Sed tempor libero ipsum, in euismod enim convallis in. Donec eu dolor ut lacus euismod porta. Etiam euismod lacinia lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse faucibus, sem eget consectetur pharetra, libero erat porttitor dui, at pharetra odio ligula in nulla.</p>
            <p>
                Morbi blandit mi ante, sit amet pulvinar nisl luctus a. Sed eget mattis enim. Etiam quis libero tincidunt, tempus neque a, pretium tellus. Praesent diam turpis, eleifend ut augue nec, placerat pretium lorem. Donec congue risus arcu, et egestas ex molestie ac. Nam aliquet, elit sit amet venenatis fringilla, est dui dignissim quam, eu varius ante nulla a lorem. Curabitur diam felis, posuere id odio sed, sagittis lobortis est. Sed eu porta turpis, vel facilisis quam.Vivamus euismod pharetra lacus at ornare. Fusce sit amet quam urna. Sed facilisis at nibh sit amet tempus. Cras a ex lacus. Nunc hendrerit et massa non placerat. Aliquam non turpis nisl. Nunc accumsan, massa non faucibus semper, nibh tellus cursus lectus, ut mollis arcu eros ac quam. Quisque nunc ante, rhoncus at tellus at, accumsan scelerisque tellus. In non consectetur quam. Sed tempor libero ipsum, in euismod enim convallis in. Donec eu dolor ut lacus euismod porta. Etiam euismod lacinia lacinia. Interdum et malesuada fames ac ante ipsum primis in. </p>

            <p>
                Morbi blandit mi ante, sit amet pulvinar nisl luctus a. Sed eget mattis enim. Etiam quis libero tincidunt, tempus neque a, pretium tellus. Praesent diam turpis, eleifend ut augue nec, placerat pretium lorem. Donec congue risus arcu, et egestas ex molestie ac. Nam aliquet, elit sit amet venenatis fringilla, est dui dignissim quam, eu varius ante nulla a lorem. Curabitur diam felis, posuere id odio sed, sagittis lobortis est. Sed eu porta turpis, vel facilisis quam.Vivamus euismod pharetra lacus at ornare. Fusce sit amet quam urna. Sed facilisis at nibh sit amet tempus. Cras a ex lacus. Nunc hendrerit et massa non placerat. Aliquam non turpis nisl. Nunc accumsan, massa non faucibus semper, nibh tellus cursus lectus, ut mollis arcu eros ac quam. Quisque nunc ante, rhoncus at tellus at, accumsan scelerisque tellus. In non consectetur quam. Sed tempor libero ipsum, in euismod enim convallis in. Donec eu dolor ut lacus euismod porta. Etiam euismod lacinia lacinia. Interdum et malesuada fames ac ante ipsum primis in. </p>

            <p>
                Morbi blandit mi ante, sit amet pulvinar nisl luctus a. Sed eget mattis enim. Etiam quis libero tincidunt, tempus neque a, pretium tellus. Praesent diam turpis, eleifend ut augue nec, placerat pretium lorem. Donec congue risus arcu, et egestas ex molestie ac. Nam aliquet, elit sit amet venenatis fringilla, est dui dignissim quam, eu varius ante nulla a lorem. Curabitur diam felis, posuere id odio sed, sagittis lobortis est. Sed eu porta turpis, vel facilisis quam.Vivamus euismod pharetra lacus at ornare. Fusce sit amet quam urna. Sed facilisis at nibh sit amet tempus. Cras a ex lacus. Nunc hendrerit et massa non placerat. Aliquam non turpis nisl. Nunc accumsan, massa non faucibus semper, nibh tellus cursus lectus, ut mollis arcu eros ac quam. Quisque nunc ante, rhoncus at tellus at, accumsan scelerisque tellus. In non consectetur quam. Sed tempor libero ipsum, in euismod enim convallis in. Donec eu dolor ut lacus euismod porta. Etiam euismod lacinia lacinia. Interdum et malesuada fames ac ante ipsum primis. </p>

            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel sapien ex. Pellentesque id ligula scelerisque metus semper vestibulum. Vivamus euismod pharetra lacus at ornare. Fusce sit amet quam urna. Sed facilisis at nibh sit amet tempus. Cras a ex lacus. Nunc hendrerit et massa non placerat. Aliquam non turpis nisl. Nunc accumsan, massa non faucibus semper, nibh tellus cursus lectus, ut mollis arcu eros ac quam. Quisque nunc ante, rhoncus at tellus at, accumsan scelerisque tellus. In non consectetur quam. Sed tempor libero ipsum, in euismod enim convallis in. Donec eu dolor ut lacus euismod porta. Etiam euismod lacinia lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse faucibus, sem eget consectetur pharetra, libero erat porttitor dui, at pharetra odio ligula in nulla.</p>
        </div>
    );
};

export default About;